### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by erikd** [Gabriel439/Haskell-Errors-Library#45]
The errors package bills itself as "The one-stop shop for all your error-handling needs!" but doesn't do ~~anything at all~ much with exceptions.

In my day job, we have an `ExceptT` combinator that seems to fit in the errors package:
```
tryEitherT :: (Functor m, MonadCatch m, Exception e) => (e -> x) -> m a -> EitherT x m a
```
if it wasn't for the `MonadCatch` and `Exceptions` constraints. I realise I can implement something close to `tryEitherT` in terms of `tryIO` but that wouldn't be as general.

Would something like `tryEitherT` be accepted into errors?

**Comment by Gabriel439** [comment]
The main reason why it doesn't deal with exceptions is that it originally was designed to use `EitherT`, converting exceptions to `EitherT` with something like `syncIO`.  However, I'd be open to adding exception-related utilities now

However, for your utility I'd suggest using `handle` in the name instead of `try` since it's much closer in spirit to `Control.Exception.handle`

**Comment by erikd** [comment]
So something like this? 
```
handleExceptT :: (Functor m, MonadCatch m) => (SomeException -> e) -> m a -> ExceptT e m a
handleExceptT handler = bimapExceptT handler id . ExceptT . try
```
This requires the addition of a dependency on exceptions, but thats about it.

**Comment by Gabriel439** [comment]
Yeah, I'm fine with depending on `exceptions`
